### PR TITLE
Feature/lora ify downloads

### PR DESCRIPTION
**Pull request by QuinnLee**
~~WIP, on translations and files~~

Added a service called `feature-toggle` to turn features on or off depending on `ENV` vars

### CODE REVIEW

**Comment by QuinnLee** [comment]
screen shot 2015-12-10 at 9 43 42 am

**Comment by makmanalp** [comment]
Hey @QuinnLee if you change the prefix to be https://s3.amazonaws.com/datlas-colombia-downloads/production/ this works :+1: . That folder will always have the latest from now on so you won't have to change the prefix ever again.

**Comment by makmanalp** [comment]
http://ci-deploys.cid-labs.com/cid-harvard/atlas-subnational-frontend/feature/lora-ify-downloads/276/#/downloads?locale=es-col

**Comment by QuinnLee** [comment]
updated and works

**Comment by makmanalp** [comment]
:+1:  works

**Pull request merged**
