### PR TITLE
Feature/location eci

### PR DESCRIPTION
**Pull request by QuinnLee**
COLOMBIA
screen shot 2015-11-06 at 2 15 46 pm
screen shot 2015-11-06 at 2 07 08 pm
screen shot 2015-11-06 at 2 06 43 pm

Translations missing, coming soon

### CODE REVIEW

**Comment by gregshap** [comment]
NiSH 
In the API & Translations & everything, we should specify ExportECI vs IndustryECI, otherwise it'll get confusing later

**Comment by QuinnLee** [comment]
agreed

**Comment by QuinnLee** [comment]
Just need copy for colombia eci `country.show.eci`

**Comment by QuinnLee** [comment]
http://ci-deploys.cid-labs.com/cid-harvard/atlas-subnational-frontend/feature/location-eci/200/

Acceptance:

MSA and DEPT profiles have export eci dotplot for those levels

COL has export ECI dotplot for departments,  COL eci value will be update with next language dump

**Pull request closed without merging**
