### PR TITLE
Graph Controls - Match designs for gb pages

### PR DESCRIPTION
**Pull request by QuinnLee**
- Match the wireframes from Katie to actual site (COL-841)
- How does this look for small multiples?
-- Keep filter on top for all graphs
-- Year (single) toggles for everything except multiples.
-- Review (COL-791)
-- button states for if transition is available. 
- Dont worry about vis-tk performance for now
- legends on top, not interactive
- RCA Toggles only for scatters

- Not on profiles
-- ideal profile visualizations will lead to GB pages

- Update  automated specs
screen shot 2016-02-09 at 11 06 14 am
screen shot 2016-02-09 at 11 06 08 am

### CODE REVIEW

**Comment by gregshap** [comment]
Some things to match the mockup a little better, which would make it better:

Instead of the long button text:
>1, < 1, All 

Instead of the red button states:
Selected vs Enabled vs Disabled .... do we have a "pattern library" for this? (by pattern library, i mean like.. some buttons anywhere that do this well?)

**Comment by QuinnLee** [comment]
> Instead of the red button states:
Selected vs Enabled vs Disabled .... do we have a "pattern library" for this? (by pattern library, i mean like.. some buttons anywhere that do this well?)

We don`t have a disabled button example.  I had to create one... There are selected, enabled ones however

**Comment by QuinnLee** [comment]
> 1, < 1, All
Updated

**Comment by QuinnLee** [comment]
screen shot 2016-02-11 at 9 28 30 am

**Comment by QuinnLee** [comment]
Update colors, light red is for disabled, there are no CSS hover for it.  Active is light grey, default is the darker gray.

**Comment by QuinnLee** [comment]
screen shot 2016-02-11 at 9 39 14 am


Disabled and active share the same css, both have `cursor:default;` update when we get a designer.

**Comment by gregshap** [comment]
On the treemaps, when I change years there's some (flexbox?) weirdness where the graph area keeps getting vertically longer and longer. Doesn't seem to be an issue for product space, scatters or geo

**Comment by QuinnLee** [comment]
Yeah, this is a weird problem with the treemap/flexbox. I just hardcoded 
in a height, 500px, to fix this.

Greg Shapiro wrote:

**Comment by gregshap** [comment]
:+1:

**Pull request merged**
