### PR TITLE
Feature/navigation header styling updates

### PR DESCRIPTION
**Pull request by QuinnLee**
screen shot 2015-12-09 at 2 15 18 pm
screen shot 2015-12-09 at 2 15 10 pm
screen shot 2015-12-09 at 2 15 05 pm

### CODE REVIEW

**Comment by QuinnLee** [comment]
http://ci-deploys.cid-labs.com/cid-harvard/atlas-subnational-frontend/feature/navigation-header-styling-updates/272/

**Comment by QuinnLee** [comment]
Added ticket #710,  

ordered the profile questions to match grouping of header
WIP, needs translation updates

**Comment by QuinnLee** [comment]
screen shot 2015-12-10 at 10 11 05 am
screen shot 2015-12-10 at 10 10 41 am
screen shot 2015-12-10 at 10 10 25 am

**Comment by QuinnLee** [comment]
http://ci-deploys.cid-labs.com/cid-harvard/atlas-subnational-frontend/feature/navigation-header-styling-updates/277/

**Comment by gregshap** [comment]
SOOOOO GOOOOOOOOOOD

**Comment by gregshap** [comment]
one question, whats the status with tooltip issues? I noticed that there are no tooltips for import origins when I'm looking at a Product:
http://ci-deploys.cid-labs.com/cid-harvard/atlas-subnational-frontend/feature/navigation-header-styling-updates/277/#/product/87/source/partners/visualization/treemap/import_value?endDate=2013&locale=es-col&startDate=2013

Same issue when I look at other products.

**Comment by QuinnLee** [comment]
@gregshap I don't know.  I can use a older version of vis-tk

**Comment by makmanalp** [comment]
:+1: 

Tooltips work on these somehow btw: http://ci-deploys.cid-labs.com/cid-harvard/atlas-subnational-frontend/feature/navigation-header-styling-updates/277/#/location/3/source/industries/visualization/treemap/employment?endDate=2013&locale=es-col&startDate=2013

**Comment by makmanalp** [comment]
I wonder if it's missing names and such?

**Comment by makmanalp** [comment]
@QuinnLee shortnames missing on my side, could that be it? http://atlas-colombia-harvard.cid-labs.com/api/metadata/countries/

**Comment by QuinnLee** [comment]
screen shot 2015-12-10 at 11 08 24 am
screen shot 2015-12-10 at 11 08 07 am

**Comment by QuinnLee** [comment]
@makmanalp negative

**Pull request merged**
