### PR TITLE
Feature/location breadcrumbs

### PR DESCRIPTION
**Pull request by QuinnLee**
screen shot 2015-11-06 at 11 24 51 am
screen shot 2015-11-06 at 11 24 34 am
screen shot 2015-11-06 at 11 24 27 am

### CODE REVIEW

**Comment by gregshap** [comment]
http://ci-deploys.cid-labs.com/cid-harvard/atlas-subnational-frontend/feature/location-breadcrumbs/111/

**Comment by QuinnLee** [comment]
@katybeck I'm not sure where the breadcrumbs should be, could you take a look?

**Comment by katybeck** [comment]
Surely! Taking a look this morning.

**Comment by QuinnLee** [comment]
On hold, will add with nav redo

**Pull request closed without merging**
