### PR TITLE
Mexico font cleaning

### PR DESCRIPTION
**Pull request by katybeck**
Removing the references to Plantin, Platform, and Circular that got missed in the switch to Open Sans.

### CODE REVIEW

**Comment by QuinnLee** [comment]
Should we also apply these to `beta` \ `master`?

**Comment by makmanalp** [comment]
http://ci-deploys.cid-labs.com/cid-harvard/atlas-subnational-frontend/mexico-font-cleaning/90/

**Comment by katybeck** [comment]
Removed font files from vendor/fonts/ directory. I'd like to hold off on removing all these from beta - this just to catch a few stragglers that the complejidad folks missed when they swapped all our faces for Open Sans.

**Comment by makmanalp** [comment]
^ looks like there's some issues in the homepage where title text is the same color as the BG. I also think this is having a tangible positive effect on page load speed, weirdly. I guess those font files were heavy, and I'm not sure they were being gzipped by the server while being transmitted, so that's something I might need to keep an eye on in the future.

**Comment by QuinnLee** [comment]
oops

**Comment by katybeck** [comment]
There's a background asset that's failing to load: 
http://ci-deploys.cid-labs.com/assets/img/acem/bg-57fd7324e90b97d478b485b4f95d6f4b.png

**Comment by QuinnLee** [comment]
screen shot 2015-11-03 at 11 09 35 am
^^ on ci branch
screen shot 2015-11-03 at 11 09 32 am
^^  on prod

I think we can't/don't have the image in CI, can someone else confirm?

**Comment by makmanalp** [comment]
Yeah, that's what it looks like to me too, hmm, ok

**Pull request merged**
