### PR TITLE
Feature/muni questions

### PR DESCRIPTION
**Pull request by QuinnLee**
COL-793
screen shot 2015-12-14 at 9 47 57 am

@gregshap

### CODE REVIEW

**Comment by gregshap** [comment]
Looks good! :+1: 
I noticed a couple other things but I'll make a separate item.

**Comment by QuinnLee** [comment]
@gregshap updated
http://ci-deploys.cid-labs.com/cid-harvard/atlas-subnational-frontend/feature/muni-questions/304/

**Comment by gregshap** [comment]
:+1: :carousel_horse:  Ride on cowboy

**Comment by makmanalp** [comment]
screen shot 2015-12-14 at 11 53 42 am

:+1:

**Pull request merged**
