### PR TITLE
Feature/occupation table country profile

### PR DESCRIPTION
**Pull request by QuinnLee**

### CODE REVIEW

**Comment by gregshap** [comment]
1. In the table, monthly wage is getting formatted to be in thousands but the column header doesn't reflect that. The download file has the whole number which is cool. It's fine to just show the whole number in both places
occupationavgmonthlywage

2. In the table and download columns, can you add Total Advertised Vacancies, or Share, or both? I think EL would just want the share, but I think Advertised Vacancies is easier to work with as long as the title is clear. (we should have spec'd it out better in jira)

**Comment by QuinnLee** [comment]
screen shot 2016-01-28 at 9 34 31 am

**Comment by QuinnLee** [comment]
>In the table, monthly wage is getting formatted to be in thousands but the column header doesn't reflect that. The download file has the whole number which is cool. It's fine to just show the whole number in both places

I'll update the translation file, but I don't want to merge in the copy changes here cause `esta` branch has alot of churn there.

**Comment by gregshap** [comment]
is there a reason not to just show the full value like 1,300,000 instead of 1,300?

**Comment by QuinnLee** [comment]
I can do this

Greg Shapiro wrote:

**Comment by QuinnLee** [comment]
screen shot 2016-01-28 at 9 46 55 am

**Comment by gregshap** [comment]
:dancer:

**Pull request merged**
