### PR TITLE
Peru locale updates

### PR DESCRIPTION
**Pull request by makmanalp**
These are the locale updates used in the meeting yesterday with Peru

### CODE REVIEW

**Comment by gregshap** [comment]
Not from this changeset, but it looks like we added census_year in the data-variables but still have census_year in all the translations files. 

Can you try removing the translations census_year?

**Comment by gregshap** [comment]
also, maybe a separate item, I suspect that the Export ECI dotplots in the location profiles are using the census_year value, so it creates a weird thing for peru where the ECI on the rankings page is different from the ECI on the profile

**Comment by makmanalp** [comment]
@gregshap re census_year, I wasn't certain which is being used, but I just checked, and it is the data-variables one so we're good, I'll remove that and other data-variables I find.

Re the ECI stuff, looks like you're right (https://github.com/cid-harvard/atlas-subnational-frontend/blob/master/app/routes/location/show.js#L137)

**Comment by QuinnLee** [comment]
@makmanalp https://github.com/cid-harvard/atlas-subnational-frontend/blob/master/app/variables/data-variables.js if you need to find the data variables.

**Comment by makmanalp** [comment]
@QuinnLee cheers :+1:

**Pull request closed without merging**
