### PR TITLE
Features/interior header menu

### PR DESCRIPTION
**Pull request by QuinnLee**
new nav

Waiting for some spanish from senior lora

screen shot 2015-11-22 at 9 40 54 pm
screen shot 2015-11-22 at 9 40 35 pm
screen shot 2015-11-22 at 9 40 18 pm

### CODE REVIEW

**Comment by QuinnLee** [comment]
http://ci-deploys.cid-labs.com/cid-harvard/atlas-subnational-frontend/features/interior-header-menu/213/

**Comment by QuinnLee** [comment]
updated with translations

**Comment by QuinnLee** [comment]
heyo, is this okay to merge?

**Comment by gregshap** [comment]
I was getting a lot of navigation highlighting bugs before, but can't reproduce now

**Comment by QuinnLee** [comment]
I pushed those fixes before i left.

Greg Shapiro wrote:

**Comment by gregshap** [comment]
missed that, is that what 61dc6af2 accomplished?

Greg Shapiro

617-943-9870
gregshap@gmail.com

**Comment by QuinnLee** [comment]
yup

**Comment by gregshap** [comment]
The only issue I have is that the text overlaps a bunch in spanish mode. (A little bit for locations, slightly worse for industries, pretty bad for products)

**Comment by katybeck** [comment]
Could that be logged as a layout bug and made into a bugfix for next sprint? The vertical version of the header layout will be in that bucket of work anyways, which will resolve a lot of that overlap.

**Comment by gregshap** [comment]
well... I don't want to do the work twice, but I also don't want to merge anything to beta with text overlap issues in the happy case. It costs too much in the first impression. I'd settle for calling the navigation story done and waiting for the layout update before merging this up. 

I should have brought it up earlier, but in general you should design for Spanish as the primary UI, and English as the secondary.

**Comment by katybeck** [comment]
Actually the correct approach is to design for all the localized languages to work — but in this case working out the distinction between what is done technically vs what is done visually seems like where we're getting hung up here.

**Comment by QuinnLee** [comment]
screen shot 2015-11-30 at 10 56 08 am
breadcrumbs for locations

**Comment by QuinnLee** [comment]
screen shot 2015-11-30 at 10 59 35 am

**Comment by gregshap** [comment]
ok do it to it. :ship:

**Pull request merged**
