### PR TITLE
Industry ECI rankings COL-934 

### PR DESCRIPTION
**Pull request by makmanalp**
screen shot 2016-04-01 at 3 31 25 pm

screen shot 2016-04-01 at 3 31 32 pm

### CODE REVIEW

**Comment by makmanalp** [comment]
Rebasing to get latest changes from beta.

**Comment by gregshap** [comment]
@makmanalp when pointing the branch to the atlas-colombia-harvard api, I get N/A for dept and city industry complexity in the rankings

**Comment by makmanalp** [comment]
@gregshap argh, my bad. One second.

**Comment by makmanalp** [comment]
@gregshap forgot to merge in the API changes - should work now. Might need to hard-refresh.

**Comment by gregshap** [comment]
:+1: good buddy

**Pull request merged**
