### PR TITLE
Hero image feature toggle / Peru hero image PERU-104

### PR DESCRIPTION
**Pull request by makmanalp**
I think it looks too busy, but this is the best we can do with the image they gave us for now.

screen shot 2016-05-07 at 7 19 45 pm

### CODE REVIEW

**Comment by QuinnLee** [comment]
Hmm, gotta do what the client whats lol

**Comment by makmanalp** [comment]
I think once they see it they'll change their minds.

**Comment by QuinnLee** [comment]
try reversing the image so the crucible is on the right :)

**Comment by makmanalp** [comment]
It's already on the right :( I cut a lot of blank space on the right part of the image to get it that far right, if I cut more then the image isn't high enough quality that it wont look pixelly

**Comment by QuinnLee** [comment]
work some CSI zoom stuff!

**Pull request merged**
