### PR TITLE
Feature/locations partner country

### PR DESCRIPTION
**Pull request by QuinnLee**
Need to update 
https://docs.google.com/spreadsheets/d/1fy27VLD3doGcI5TIAEU_x1l4BgSd761J5Y9n1BZHs0M/edit#gid=274296755

screen shot 2015-11-10 at 12 33 50 pm
screen shot 2015-11-10 at 12 36 17 pm

### CODE REVIEW

**Comment by gregshap** [comment]
http://ci-deploys.cid-labs.com/cid-harvard/atlas-subnational-frontend/feature/locations-partner-country/135/

**Comment by QuinnLee** [comment]
@makmanalp is the api down for partner countries?
http://ci-deploys.cid-labs.com/cid-harvard/atlas-subnational-frontend/feature/locations-partner-country/178/#/graph_builder/location-1/source/partners/visualization/treemap?endDate=2013&startDate=2013&variable=export_value

**Comment by QuinnLee** [comment]
also enable for Colombia and MSA, disabled for Muni

**Comment by QuinnLee** [comment]
Copy has been updated

**Comment by QuinnLee** [comment]
http://ci-deploys.cid-labs.com/cid-harvard/atlas-subnational-frontend/feature/locations-partner-country/194/

Acceptance Condition:
MSA and Departments have export partners
Table show exports and year

**Pull request merged**
