### PR TITLE
Feature/vistk scatterplots

### PR DESCRIPTION
**Pull request by romsson**
screen shot 2015-11-04 at 1 32 58 pm

### CODE REVIEW

**Comment by gregshap** [comment]
http://ci-deploys.cid-labs.com/cid-harvard/atlas-subnational-frontend/feature/vistk-scatterplots/100/

**Comment by gregshap** [comment]
is this ready for review again? the main issue iirc was that the current ECI line moves around when you filter

**Comment by QuinnLee** [comment]
Looks good

The only thing I think we should fix is the components name spacing 

>Note: Components must have a dash in their name. So blog-post is an acceptable name, but post is not. This prevents clashes with current or future HTML element names, and ensures Ember picks up the components automatically.

http://guides.emberjs.com/v1.12.0/components/defining-a-component/

Maybe we can do `vistk-<vis-name>`?

**Comment by romsson** [comment]
agreed to prepend the toolkit name.
also, we should probably have more consistent names for styles, filenames and internal variables (for the latter I have in mind the similarity/network/product-space viz which now has so many different names).

**Comment by gregshap** [comment]
:rocket: ship it

**Comment by QuinnLee** [comment]
soon

Greg Shapiro wrote:

**Pull request merged**
