### PR TITLE
Feature/profile nav question

### PR DESCRIPTION
**Pull request by QuinnLee**
Product profile
=============
screen shot 2015-12-03 at 4 09 01 pm

Industry profile
============
screen shot 2015-12-03 at 4 04 56 pm

Location Profile
============
col
------
screen shot 2015-12-03 at 4 06 50 pm
muni
-------
screen shot 2015-12-03 at 4 06 31 pm
dept
------
screen shot 2015-12-03 at 4 06 07 pm
msa
--------
screen shot 2015-12-03 at 3 54 14 pm

About Pages
================
screen shot 2015-12-03 at 3 54 04 pm
screen shot 2015-12-03 at 3 54 00 pm
screen shot 2015-12-03 at 3 53 53 pm

### CODE REVIEW

**Comment by QuinnLee** [comment]
http://ci-deploys.cid-labs.com/cid-harvard/atlas-subnational-frontend/feature/profile-nav-question/251

**Comment by makmanalp** [comment]
COL-780 :+1: 
COL-781 :+1:

**Comment by makmanalp** [comment]
COL-778 still seems to be overflowing text in the spanish translation, but you folks knew that already

**Comment by makmanalp** [comment]
all checked on firefox

**Comment by QuinnLee** [comment]
>COL-778 still seems to be overflowing text in the spanish translation, but you folks knew that already

Yup, that is in another ticket for the header.

**Pull request merged**
