### PR TITLE
Feature/update table download

### PR DESCRIPTION
**Pull request by QuinnLee**
file downloads from the table match table view 
screen shot 2015-11-03 at 4 55 31 pm
screen shot 2015-11-03 at 4 55 28 pm
screen shot 2015-11-03 at 4 55 27 pm

### CODE REVIEW

**Comment by gregshap** [comment]
http://ci-deploys.cid-labs.com/cid-harvard/atlas-subnational-frontend/feature/update-table-download/107/

**Comment by gregshap** [comment]
Can you deburr and de-upside down question mark the filename as well?

**Comment by QuinnLee** [comment]
soon

**Comment by gregshap** [comment]
kind of meh:
In download file the column title is "Total wages, Col$ (in thousands)" but the values are full numbers, not in thousands.

http://localhost:4200/graph_builder/location-87/source/industries/visualization/scatter?endDate=2013&locale=en-col&startDate=2013

**Comment by gregshap** [comment]
It would be nice to truncate/round the other columns as we show them in the gbuilder table. Not a show stopper but weird to say employment="3298.083496"

**Comment by QuinnLee** [comment]
This is true, but I dont want to implement a number formatting in the 
downloads. This is a data issue imo

Greg Shapiro wrote:

**Comment by gregshap** [comment]
Sure, I'll agree with that about rounding. No need to pass a million digits after the decimal all the way to the frontend.

**Comment by gregshap** [comment]
Whats the best move for (thousands) though?

**Comment by QuinnLee** [comment]
updated to have better column names and deburr file names

**Comment by QuinnLee** [comment]
upside down ? is still there.  Deburr doesn't remove it

**Comment by gregshap** [comment]
but but, deburr AND ¿de-upside down question mark?
It's just visual but it "looks" buggy. 

¿Why let perceived bugginess besmirch an otherwise fantastic feature?

**Comment by QuinnLee** [comment]
how about `string.replace(/[^\w\s]/gi, '')`

Greg Shapiro wrote:

**Comment by gregshap** [comment]
ya, though maybe so it's more readable: [^A-Za-z0-9\-_\s]

**Comment by gregshap** [comment]
^after deburring

**Comment by gregshap** [comment]
that trailing hyphen gotta go though

**Comment by QuinnLee** [comment]
updated
screen shot 2015-11-09 at 10 06 50 am

**Comment by QuinnLee** [comment]
merge?

**Comment by gregshap** [comment]
retroactive :+1:

**Comment by QuinnLee** [comment]
I was given the verbal "let it so, number 1"

Greg Shapiro wrote:

**Comment by gregshap** [comment]
http://media.giphy.com/media/sIfvjuG26APYI/giphy.gif

**Pull request merged**
